sudo: required

services:
  - docker

before_install:
  - docker build -t lavagupta/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run lavagupta/react-test npm test -- --coverage

after_success:
  - docker build -t lavagupta/multi-client ./client
  - docker build -t lavagupta/multi-nginx ./nginx
  - docker build -t lavagupta/multi-server ./server
  - docker build -t lavagupta/multi-worker ./worker
     ### Docker Login ####
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  #### Push the images ###
  - docker push lavagupta/multi-client
  - docker push lavagupta/multi-nginx
  - docker push lavagupta/multi-server
  - docker push lavagupta/multi-worker